services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - nginx

  processor1:
    build: ./processor
    container_name: processor1
    ports:
      - "4000:4000"

  processor2:
    build: ./processor
    container_name: processor2
    ports:
      - "4001:4000"

  notifier:
    build: ./notifier
    ports:
      - "5002:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - processor1
      - processor2